export type Technology =
  | "Core Java"
  | "Python"
  | "Manual Testing"
  | "Automation Testing"
  | "Selenium"
  | "SQL"
  | "HTML"
  | "CSS"
  | "JavaScript"
  | "React";

export type Difficulty = "Beginner" | "Intermediate" | "Advanced";

export interface Question {
  id: number;
  question: string;
  options: string[];
  correctAnswer: number;
  explanation: string;
  type: "mcq" | "scenario" | "conceptual";
}

export interface TestResult {
  technology: Technology;
  difficulty: Difficulty;
  totalQuestions: number;
  correctAnswers: number;
  wrongAnswers: number;
  scorePercentage: number;
  answers: Record<number, number>;
  questions: Question[];
  timeTaken: number;
}

export const technologies: { name: Technology; icon: string; description: string }[] = [
  { name: "Core Java", icon: "☕", description: "Object-oriented programming, JVM, collections, and more" },
  { name: "Python", icon: "🐍", description: "Scripting, data structures, OOP, and libraries" },
  { name: "Manual Testing", icon: "🔍", description: "Test cases, bug lifecycle, SDLC, and methodologies" },
  { name: "Automation Testing", icon: "🤖", description: "Frameworks, CI/CD, test automation strategies" },
  { name: "Selenium", icon: "🌐", description: "WebDriver, locators, waits, and frameworks" },
  { name: "SQL", icon: "🗄️", description: "Queries, joins, normalization, and optimization" },
  { name: "HTML", icon: "📄", description: "Elements, forms, semantics, and accessibility" },
  { name: "CSS", icon: "🎨", description: "Layouts, flexbox, grid, animations, and responsive design" },
  { name: "JavaScript", icon: "⚡", description: "ES6+, DOM, async programming, and closures" },
  { name: "React", icon: "⚛️", description: "Components, hooks, state management, and routing" },
];

// Mock question bank - in production these would come from AI
const questionBanks: Record<string, Question[]> = {
  "Core Java-Beginner": [
    { id: 1, question: "Which of the following is the correct way to declare a variable in Java?", options: ["int x = 10;", "x = 10 int;", "declare int x = 10;", "variable x = 10;"], correctAnswer: 0, explanation: "In Java, variables are declared with the type first, followed by the name and optional initialization.", type: "mcq" },
    { id: 2, question: "What is the output of: System.out.println(5 + 3 + \"hello\");?", options: ["53hello", "8hello", "hello53", "hello8"], correctAnswer: 1, explanation: "Java evaluates left to right. 5+3=8 (integer addition), then 8+\"hello\" = \"8hello\" (string concatenation).", type: "mcq" },
    { id: 3, question: "Which keyword is used to inherit a class in Java?", options: ["implements", "extends", "inherits", "super"], correctAnswer: 1, explanation: "The 'extends' keyword is used to inherit a class in Java.", type: "mcq" },
    { id: 4, question: "What is the default value of an int variable in Java?", options: ["null", "0", "undefined", "1"], correctAnswer: 1, explanation: "The default value of an int variable in Java is 0.", type: "conceptual" },
    { id: 5, question: "A developer notices that their ArrayList is throwing ConcurrentModificationException during iteration. What is the most likely cause?", options: ["The list is null", "The list is being modified while iterating with a for-each loop", "The list has duplicate elements", "The list exceeds memory"], correctAnswer: 1, explanation: "Modifying an ArrayList during iteration with for-each or Iterator without using Iterator.remove() throws ConcurrentModificationException.", type: "scenario" },
    { id: 6, question: "Which of the following is NOT a primitive data type in Java?", options: ["int", "boolean", "String", "char"], correctAnswer: 2, explanation: "String is a class in Java, not a primitive data type. The eight primitives are byte, short, int, long, float, double, boolean, and char.", type: "mcq" },
    { id: 7, question: "What does JVM stand for?", options: ["Java Virtual Machine", "Java Variable Manager", "Java Version Module", "Java Visual Machine"], correctAnswer: 0, explanation: "JVM stands for Java Virtual Machine, which is responsible for executing Java bytecode.", type: "conceptual" },
    { id: 8, question: "Which method is the entry point of a Java application?", options: ["start()", "run()", "main()", "init()"], correctAnswer: 2, explanation: "The main() method with signature 'public static void main(String[] args)' is the entry point.", type: "mcq" },
    { id: 9, question: "What is the size of an int in Java?", options: ["16 bits", "32 bits", "64 bits", "Platform dependent"], correctAnswer: 1, explanation: "An int in Java is always 32 bits (4 bytes), regardless of the platform.", type: "mcq" },
    { id: 10, question: "A team is building a banking application. They need to store monetary values precisely. Which data type should they use?", options: ["float", "double", "BigDecimal", "int"], correctAnswer: 2, explanation: "BigDecimal should be used for precise monetary calculations as float and double can have rounding errors.", type: "scenario" },
    { id: 11, question: "What is the purpose of the 'final' keyword in Java?", options: ["To end a program", "To prevent modification of a variable, method, or class", "To finalize garbage collection", "To declare constants only"], correctAnswer: 1, explanation: "The 'final' keyword prevents a variable from being reassigned, a method from being overridden, or a class from being inherited.", type: "conceptual" },
    { id: 12, question: "Which operator is used for string comparison in Java?", options: ["==", "equals()", "compare()", "==="], correctAnswer: 1, explanation: "The equals() method compares string content. The == operator compares references, not content.", type: "mcq" },
    { id: 13, question: "What is autoboxing in Java?", options: ["Automatic packaging of code", "Automatic conversion between primitive types and wrapper classes", "Automatic memory allocation", "Automatic type casting"], correctAnswer: 1, explanation: "Autoboxing is the automatic conversion between primitive types (like int) and their wrapper classes (like Integer).", type: "conceptual" },
    { id: 14, question: "Which collection interface does NOT allow duplicate elements?", options: ["List", "Set", "Queue", "Deque"], correctAnswer: 1, explanation: "The Set interface does not allow duplicate elements. Lists, Queues, and Deques can contain duplicates.", type: "mcq" },
    { id: 15, question: "What is the output of: System.out.println(10 / 3);?", options: ["3.33", "3", "3.0", "Error"], correctAnswer: 1, explanation: "Integer division in Java truncates the decimal. 10/3 = 3 (integer result).", type: "mcq" },
    { id: 16, question: "A developer creates an object but never uses it again. What happens to the memory?", options: ["Memory leak occurs", "Garbage collector reclaims it", "Program crashes", "It stays forever"], correctAnswer: 1, explanation: "Java's garbage collector automatically reclaims memory of objects that are no longer referenced.", type: "scenario" },
    { id: 17, question: "What is the difference between '==' and '.equals()' for objects?", options: ["No difference", "'==' compares references, '.equals()' compares content", "'==' compares content, '.equals()' compares references", "Both compare content"], correctAnswer: 1, explanation: "'==' checks if two references point to the same object in memory, while '.equals()' checks if two objects have the same value.", type: "conceptual" },
    { id: 18, question: "Which access modifier makes a member accessible only within its own class?", options: ["public", "protected", "default", "private"], correctAnswer: 3, explanation: "The 'private' access modifier restricts access to within the declaring class only.", type: "mcq" },
    { id: 19, question: "What is a constructor in Java?", options: ["A method that destroys objects", "A special method called when an object is created", "A method that returns a value", "A static method"], correctAnswer: 1, explanation: "A constructor is a special method invoked when an object is instantiated. It initializes the object's state.", type: "conceptual" },
    { id: 20, question: "You need to store key-value pairs where keys must be unique. Which collection should you use?", options: ["ArrayList", "LinkedList", "HashMap", "HashSet"], correctAnswer: 2, explanation: "HashMap stores key-value pairs with unique keys. It provides O(1) average time for put and get operations.", type: "scenario" },
  ],
  "Manual Testing-Beginner": [
    { id: 1, question: "What is the primary purpose of manual testing?", options: ["To write scripts", "To find bugs by executing test cases manually", "To automate test cases", "To design the application"], correctAnswer: 1, explanation: "Manual testing involves manually executing test cases to identify defects in the software without using automation tools.", type: "conceptual" },
    { id: 2, question: "Which document outlines the steps to be executed for testing?", options: ["Test Plan", "Test Scenario", "Test Case", "Bug Report"], correctAnswer: 2, explanation: "A test case contains a detailed set of steps, expected results, and test data.", type: "mcq" },
    { id: 3, question: "What is a 'bug' in the context of software testing?", options: ["A feature", "An error, flaw, or fault in the software", "A user requirement", "A type of test"], correctAnswer: 1, explanation: "A bug is a defect that causes the software to behave in an unintended way.", type: "conceptual" },
    { id: 4, question: "A tester is checking if a 'Forgot Password' link works as expected. What type of testing is this?", options: ["Performance Testing", "Functional Testing", "Security Testing", "Usability Testing"], correctAnswer: 1, explanation: "Functional testing verifies that each function of the software application operates in conformance with the requirements specification.", type: "scenario" },
    { id: 5, question: "What is the first stage in the Bug Life Cycle?", options: ["Open", "New", "Assigned", "Fixed"], correctAnswer: 1, explanation: "When a defect is first identified and reported, it is in the 'New' state.", type: "mcq" },
    { id: 6, question: "Which of these is a 'non-functional' testing type?", options: ["Unit Testing", "Integration Testing", "Performance Testing", "Regression Testing"], correctAnswer: 2, explanation: "Non-functional testing checks aspects like performance, usability, and reliability, not specific features.", type: "mcq" },
    { id: 7, question: "What does 'SDLC' stand for?", options: ["Software Development Life Cycle", "System Design Life Cycle", "Software Design Logic Control", "System Development Logic Cycle"], correctAnswer: 0, explanation: "SDLC is the process followed for a software project, within a software organization.", type: "conceptual" },
    { id: 8, question: "When you test the main functionalities of a new build to see if it's stable enough for further testing, what is it called?", options: ["Regression Testing", "Sanity Testing", "Smoke Testing", "Monkey Testing"], correctAnswer: 2, explanation: "Smoke testing is a preliminary check to ensure the most critical functions of a program work.", type: "mcq" },
    { id: 9, question: "A login form requires a username and password. You test it by entering a valid username and a valid password. This is an example of:", options: ["Negative Testing", "Positive Testing", "Destructive Testing", "Boundary Testing"], correctAnswer: 1, explanation: "Positive testing checks if the system behaves as expected with valid inputs.", type: "scenario" },
    { id: 10, question: "What is the purpose of a Test Plan?", options: ["To write code", "To outline the strategy, scope, resources, and schedule of testing", "To fix bugs", "To execute tests"], correctAnswer: 1, explanation: "A test plan is a comprehensive document that guides the entire testing process.", type: "conceptual" },
    { id: 11, question: "Which of the following is NOT a standard component of a test case?", options: ["Test Case ID", "Developer's Name", "Expected Result", "Test Steps"], correctAnswer: 1, explanation: "While a tester's name might be on a test case, the developer's name is not a standard component.", type: "mcq" },
    { id: 12, question: "What is 'Black Box Testing'?", options: ["Testing with knowledge of the internal code", "Testing without knowledge of the internal code", "Testing only the database", "Testing only the user interface"], correctAnswer: 1, explanation: "In Black Box Testing, the tester does not need to know the internal workings of the application.", type: "conceptual" },
    { id: 13, question: "A bug was found and fixed. What is the immediate next step for the tester?", options: ["Close the bug", "Retest the fix", "Find another bug", "Write a new test plan"], correctAnswer: 1, explanation: "After a bug is fixed, the tester must verify that the fix works correctly by retesting.", type: "mcq" },
    { id: 14, question: "You are testing a field that accepts ages from 18 to 60. You test with the values 17, 18, 19, 59, 60, and 61. What is this technique called?", options: ["Equivalence Partitioning", "Boundary Value Analysis", "State Transition Testing", "Random Testing"], correctAnswer: 1, explanation: "Boundary Value Analysis focuses on testing the values at the edges of an input domain.", type: "scenario" },
    { id: 15, question: "What is Regression Testing?", options: ["Testing a specific new feature", "Retesting a fixed bug", "Testing to ensure new changes haven't broken existing functionality", "Testing the application for the first time"], correctAnswer: 2, explanation: "Regression testing is crucial for ensuring that updates do not have unintended negative consequences.", type: "conceptual" },
    { id: 16, question: "Which of these testing levels is performed by developers?", options: ["System Testing", "Unit Testing", "Acceptance Testing", "Beta Testing"], correctAnswer: 1, explanation: "Unit Testing is typically performed by the developer who wrote the code to test individual components.", type: "mcq" },
    { id: 17, question: "What is the difference between Verification and Validation?", options: ["They are the same", "Verification is checking documents, Validation is testing the software", "Verification is 'Are we building the product right?', Validation is 'Are we building the right product?'", "Verification is done by testers, Validation by developers"], correctAnswer: 2, explanation: "Verification focuses on requirements and design, while Validation focuses on the final product meeting user needs.", type: "conceptual" },
    { id: 18, question: "You are exploring the application without any test cases, based on your experience. This is called:", options: ["Formal Testing", "Exploratory Testing", "Structured Testing", "Ad-hoc Testing"], correctAnswer: 1, explanation: "Exploratory testing relies on the tester's freedom and creativity to discover issues.", type: "mcq" },
    { id: 19, question: "A website is slow to load. This is a defect related to:", options: ["Functionality", "Usability", "Performance", "Compatibility"], correctAnswer: 2, explanation: "Performance testing evaluates the speed, responsiveness, and stability of a system.", type: "scenario" },
    { id: 20, question: "What does 'STLC' stand for?", options: ["Software Testing Life Cycle", "System Test Logic Control", "Software Test Lead Center", "System Testing Life Cycle"], correctAnswer: 0, explanation: "The STLC is a sequence of activities conducted during the software testing process.", type: "conceptual" }
  ],
  "Manual Testing-Intermediate": [
    { id: 1, question: "What is the key difference between a Test Plan and a Test Strategy?", options: ["Test Plan is for a project, Test Strategy is for an organization", "Test Strategy is a part of Test Plan", "Test Plan has a schedule, Test Strategy does not", "They are the same"], correctAnswer: 0, explanation: "A Test Strategy is a high-level document for the organization, while a Test Plan is a detailed document for a specific project.", type: "conceptual" },
    { id: 2, question: "In which testing technique do you divide input data into classes from which test cases can be derived?", options: ["Boundary Value Analysis", "Equivalence Partitioning", "Decision Table Testing", "State Transition Testing"], correctAnswer: 1, explanation: "Equivalence Partitioning helps reduce the number of test cases by assuming all values in a partition will behave the same.", type: "mcq" },
    { id: 3, question: "What is the main purpose of a Traceability Matrix?", options: ["To track defects", "To map requirements to test cases", "To schedule testing activities", "To manage test environments"], correctAnswer: 1, explanation: "A Requirement Traceability Matrix ensures that all requirements are covered by test cases.", type: "conceptual" },
    { id: 4, question: "A developer fixes a bug, but the fix introduces a new bug in a different part of the application. To catch this, a tester should perform:", options: ["Retesting", "Smoke Testing", "Regression Testing", "Sanity Testing"], correctAnswer: 2, explanation: "Regression testing is specifically designed to uncover new defects in existing functionality.", type: "scenario" },
    { id: 5, question: "Distinguish between Priority and Severity of a defect.", options: ["They are the same", "Priority is impact on business, Severity is impact on functionality", "Severity is impact on business, Priority is impact on functionality", "Priority is for developers, Severity is for testers"], correctAnswer: 1, explanation: "Severity denotes the technical impact of the bug, while Priority denotes the urgency of fixing it from a business perspective.", type: "conceptual" },
    { id: 6, question: "What is 'White Box Testing'?", options: ["Testing without seeing the code", "Testing based on the internal structure of the code", "Another name for Black Box Testing", "Testing performed by the end-user"], correctAnswer: 1, explanation: "White Box Testing requires knowledge of the code and is often performed by developers.", type: "mcq" },
    { id: 7, question: "When is it appropriate to perform Sanity Testing?", options: ["At the very beginning of the project", "After a build has passed Smoke Testing, to check specific functionality", "After the software is released", "Only when a critical bug is found"], correctAnswer: 1, explanation: "Sanity testing is a quick check on a specific area of functionality after a change or fix, to ensure it works and hasn't broken anything obvious.", type: "mcq" },
    { id: 8, question: "You are testing an ATM. You test the sequence of inserting a card, entering a PIN, and withdrawing cash. This is an example of what kind of testing technique?", options: ["Decision Table", "Use Case Testing", "Static Testing", "Exploratory Testing"], correctAnswer: 1, explanation: "Use Case Testing focuses on executing business scenarios or 'use cases' from an end-user perspective.", type: "scenario" },
    { id: 9, question: "What are 'exit criteria' in a Test Plan?", options: ["The conditions to start testing", "The conditions to stop testing", "The team members involved", "The list of features to be tested"], correctAnswer: 1, explanation: "Exit criteria define the state at which testing can be considered complete, such as test case pass rate or no open critical defects.", type: "conceptual" },
    { id: 10, question: "What is the primary goal of End-to-End Testing?", options: ["To test individual modules", "To test the flow of an application from start to finish", "To test the database", "To test only the UI"], correctAnswer: 1, explanation: "End-to-End testing validates the entire system, including its integrations with external interfaces, simulating a real user scenario.", type: "conceptual" },
    { id: 11, question: "Which of the following is an example of Static Testing?", options: ["Executing a test case", "Reviewing a requirements document", "Running a performance test", "Performing usability testing"], correctAnswer: 1, explanation: "Static testing involves examining documents and code without executing the software itself. Reviews and walkthroughs are common examples.", type: "mcq" },
    { id: 12, question: "A bug is reproducible on the test environment but not on the development environment. What is the most likely first step to resolve this?", options: ["Close the bug as 'Not Reproducible'", "Ask the developer to test again", "Compare environment configurations (e.g., OS, data, dependencies)", "Immediately escalate to the project manager"], correctAnswer: 2, explanation: "Discrepancies between environments are a common cause of such issues. Aligning configurations is the first logical step.", type: "scenario" },
    { id: 13, question: "What is 'Error Guessing'?", options: ["A formal test design technique with guaranteed results", "An experience-based technique where testers guess where errors might occur", "Randomly clicking through the application", "A type of automated testing"], correctAnswer: 1, explanation: "Error guessing leverages the tester's intuition and experience with similar applications to find defects.", type: "conceptual" },
    { id: 14, question: "Which phase of the STLC involves writing test cases?", options: ["Test Planning", "Test Design", "Test Execution", "Test Closure"], correctAnswer: 1, explanation: "During the Test Design phase, test cases and test scenarios are created based on the requirements.", type: "mcq" },
    { id: 15, question: "You are testing a feature that calculates shipping costs based on weight and distance. Which test design technique is most suitable for this?", options: ["State Transition Testing", "Exploratory Testing", "Decision Table Testing", "Use Case Testing"], correctAnswer: 2, explanation: "A Decision Table is ideal for testing complex business logic with multiple conditions and outcomes.", type: "scenario" },
    { id: 16, question: "What is Beta Testing?", options: ["Testing done by internal developers", "Testing done by a select group of end-users before official release", "The first phase of testing", "Another name for System Testing"], correctAnswer: 1, explanation: "Beta testing gathers feedback from real users in their own environment.", type: "conceptual" },
    { id: 17, question: "What does 'Test Coverage' measure?", options: ["The number of bugs found", "The amount of time spent testing", "The extent to which a given test suite tests a requirement or code", "The number of testers on a project"], correctAnswer: 2, explanation: "Test coverage metrics help evaluate the thoroughness of the testing effort.", type: "mcq" },
    { id: 18, question: "What is the difference between retesting and regression testing?", options: ["They are the same", "Retesting confirms a specific fix; Regression checks for unexpected side-effects", "Regression confirms a specific fix; Retesting checks for unexpected side-effects", "Retesting is automated; Regression is manual"], correctAnswer: 1, explanation: "Retesting is a focused verification of a fix, while regression testing has a broader scope of ensuring overall stability.", type: "conceptual" },
    { id: 19, "question": "A defect is marked as 'Deferred'. What does this mean?", options: ["It has been fixed", "It will be fixed in a future release", "It is not a real bug", "The bug is being re-tested"], correctAnswer: 1, explanation: "A deferred defect is acknowledged but postponed, usually because it's low priority or there isn't enough time in the current cycle.", type: "mcq" },
    { id: 20, question: "While testing a web application, you find a broken link. What is the severity and priority you would assign?", options: ["High Severity, High Priority", "Low Severity, Low Priority", "Depends on the link's importance (e.g., 'Login' vs. 'Privacy Policy')", "High Severity, Low Priority"], correctAnswer: 2, explanation: "The impact and urgency depend on context. A broken 'Buy Now' link is critical, while a broken link in an old blog post is not.", type: "scenario" }
  ],
  "Manual Testing-Advanced": [
    { id: 1, question: "How would you create a Test Strategy for a project with vague or incomplete requirements?", options: ["Refuse to test until requirements are complete", "Focus on exploratory testing and risk-based analysis", "Write test cases based on assumptions", "Only perform performance testing"], correctAnswer: 1, explanation: "In such cases, a risk-based approach combined with exploratory testing allows testers to provide value by focusing on critical areas and discovering issues even without detailed specs.", type: "scenario" },
    { id: 2, question: "What is the fundamental difference between the Waterfall and Agile models from a testing perspective?", options: ["There is no testing in Waterfall", "Testing is a separate phase at the end in Waterfall, but is continuous in Agile", "Testing is only automated in Agile", "Testing is more important in Waterfall"], correctAnswer: 1, explanation: "Agile methodologies integrate testing throughout the development lifecycle, whereas in Waterfall, it's a distinct, sequential phase.", type: "conceptual" },
    { id: 3, question: "Explain the concept of 'Shift-Left Testing'.", options: ["Testing only at the end of the cycle", "Starting testing activities earlier in the development lifecycle", "Shifting all testers to the left side of the office", "Delaying testing until the UI is complete"], correctAnswer: 1, explanation: "Shift-left testing aims to find and prevent defects early by involving testers in activities like requirements analysis and design reviews.", type: "conceptual" },
    { id: 4, question: "You are asked to determine the root cause of a recurring production bug that test teams failed to catch. What is your process?", options: ["Blame the developers", "Perform a Root Cause Analysis (RCA) by analyzing logs, test cases, and the development process", "Immediately write a new set of regression tests", "Demand more testers for the team"], correctAnswer: 1, explanation: "A formal RCA (e.g., using the '5 Whys' technique) is a systematic way to identify the underlying problem, which could be a gap in test coverage, environment issues, or a process failure.", type: "scenario" },
    { id: 5, question: "What are the pros and cons of using a Test Management Tool like Jira or TestRail?", options: ["They only add unnecessary overhead", "Pros: Traceability, collaboration, reporting. Cons: Cost, learning curve, maintenance.", "They are only useful for automated testing", "They replace the need for a Test Plan"], correctAnswer: 1, explanation: "While powerful for managing complex projects, these tools require investment in terms of licensing, setup, and training.", type: "conceptual" },
    { id: 6, question: "Describe how you would test for localization (l10n) and internationalization (i18n).", options: ["Just check if the language changes", "Internationalization (i18n) is designing the app to be adaptable; Localization (l10n) is adapting it for a specific region (language, currency, formats)", "They are the same as usability testing", "This is a developer's task only"], correctAnswer: 1, explanation: "i18n is the foundational design, while l10n is the process of testing the specific adaptations for different locales.", type: "conceptual" },
    { id: 7, question: "What is 'Pair Testing' and when is it useful?", options: ["Two testers testing different applications simultaneously", "A developer and a tester working together at one machine to test a feature", "A competition between two testers", "A type of automated test"], correctAnswer: 1, explanation: "Pair testing is a collaborative approach where a developer and tester work together. It's useful for complex features and for immediate bug fixing.", type: "conceptual" },
    { id: 8, question: "How does the concept of a 'Test Pyramid' influence your test strategy?", options: ["It means you should have more UI tests than any other type", "It suggests a healthy portfolio of tests: a large base of fast unit tests, fewer integration tests, and a small number of slow E2E/UI tests", "It's a diagram of the testing team structure", "It applies only to Agile projects"], correctAnswer: 1, explanation: "The test pyramid is a strategy for a fast, stable, and reliable test suite, emphasizing foundational unit tests over slow, brittle UI tests.", type: "conceptual" },
    { id: 9, question: "A critical payment API is failing intermittently. It works 9 out of 10 times. How do you approach testing this?", options: ["Ignore it as it mostly works", "Report it as low priority", "Try to identify a pattern by analyzing logs, timestamps, and request payloads. Consider load and concurrency issues.", "Blame network issues and close the ticket"], correctAnswer: 2, explanation: "Intermittent bugs are often the most difficult. A systematic approach is needed to find patterns related to load, specific data, or timing (race conditions).", type: "scenario" },
    { id: 10, question: "What is the role of a tester in a CI/CD (Continuous Integration/Continuous Deployment) pipeline?", options: ["The tester has no role; it's fully automated", "Testers define and maintain automated test suites (smoke, regression) that run in the pipeline, and perform exploratory testing on new features", "To manually approve every build", "To only test at the end of the pipeline"], correctAnswer: 1, explanation: "In CI/CD, testers become automation gatekeepers, ensuring quality at every stage of the pipeline, and supplement automation with manual exploratory testing.", type: "conceptual" },
    { id: 11, question: "How would you test a chatbot's conversational flow and intent recognition?", options: ["Only test if it responds", "Test for specific keywords, but also for synonyms, misspellings, and out-of-context questions. Use decision trees to map conversations.", "This cannot be tested manually", "Verify it can handle at least 100 users at once"], correctAnswer: 1, explanation: "Testing a chatbot requires checking its Natural Language Processing (NLP) capabilities, including understanding user intent even with varied inputs.", type: "scenario" },
    { id: 12, question: "Explain 'Risk-Based Testing'.", options: ["Testing only high-risk features and ignoring everything else", "A strategy that prioritizes testing features based on their assessed risk (probability of failure x impact of failure)", "A type of security testing", "Eliminating all risks before testing"], correctAnswer: 1, explanation: "Risk-based testing is a practical approach to direct testing efforts where they are most needed, maximizing the impact of a limited testing timeframe.", type: "conceptual" },
    { id: 13, question: "What are heuristics in software testing?", options: ["Strict rules that must always be followed", "Mental shortcuts or rules of thumb (e.g., 'every input field must be validated') to guide testing", "A type of test automation framework", "A test management tool"], correctAnswer: 1, explanation: "Heuristics, like the 'CRUD' (Create, Read, Update, Delete) heuristic for data-driven applications, provide a framework for rapid test idea generation.", type: "conceptual" },
    { id: 14, question: "You're testing a mobile app and notice it drains the battery very quickly. How would you quantify and report this issue?", options: ["Report 'the battery drains fast'", "Use profiling tools to measure battery consumption over a specific period of activity and compare it against a baseline or a similar app", "Suggest users should carry a charger", "Assume it's a hardware problem"], correctAnswer: 1, explanation: "A good bug report for performance issues includes objective data. Profiling provides the necessary metrics to show the severity of the problem.", type: "scenario" },
    { id: 15, question: "What is the difference between Alpha and Beta testing?", options: ["Alpha is by developers, Beta is by testers", "Alpha testing is internal (by employees); Beta testing is external (by real users)", "Alpha is for mobile apps, Beta is for web apps", "They are the same"], correctAnswer: 1, explanation: "Alpha testing is a form of internal acceptance testing, while Beta testing is a form of external user acceptance testing.", type: "conceptual" },
    { id: 16, question: "How can a tester contribute to improving the overall software development process, beyond just finding bugs?", options: ["A tester's job is only to find bugs", "By providing feedback on requirements, participating in design reviews, and analyzing bug trends to suggest process improvements", "By writing code for the application", "By managing the project schedule"], correctAnswer: 1, explanation: "A mature QA professional takes a proactive role in quality assurance, not just quality control (defect detection).", type: "conceptual" },
    { id: 17, question: "What challenges might you face when testing a microservices-based architecture?", options: ["There are no challenges", "Complexity in integration testing, need for contract testing between services, and difficulty in end-to-end monitoring and debugging", "It's easier to test than a monolith", "Microservices do not require testing"], correctAnswer: 1, explanation: "While microservices offer scalability, they introduce new testing challenges related to inter-service communication and distributed data.", type: "conceptual" },
    { id: 18, "question": "What is 'Mutation Testing'?", options: ["A type of regression testing", "A technique to evaluate the quality of your tests by introducing small faults (mutations) into the code and checking if your tests fail", "Testing for genetic algorithms", "Randomly changing the code to see what happens"], correctAnswer: 1, explanation: "If your tests don't fail when the code is deliberately broken, it indicates your test suite is not effective enough. This is a white-box technique.", type: "conceptual" },
    { id: 19, question: "You are given a legacy application with no documentation. How do you begin testing?", options: ["Refuse the task", "Start with extensive exploratory testing to understand the application's behavior and build a mental model of its functionality", "Immediately try to automate it", "Wait for the original developers to be rehired"], correctAnswer: 1, explanation: "For legacy systems, exploratory testing is the most effective initial approach to discover functionality, map out user flows, and identify high-risk areas.", type: "scenario" },
    { id: 20, question: "How do you ensure your manual testing efforts are not redundant with automated tests?", options: ["Stop all manual testing", "Focus manual testing on areas that are difficult to automate, like usability, UX, and complex exploratory scenarios", "Run the automated tests manually", "Only automate tests after they have been manually executed for a year"], correctAnswer: 1, explanation: "Effective test strategies use manual and automated testing to complement each other. Manual testing should cover areas where human observation and intuition provide the most value.", type: "conceptual" }
  ],
};

// Generate questions for any tech/difficulty combo by reusing and adapting the bank
export function generateMockQuestions(technology: Technology, difficulty: Difficulty): Question[] {
  const key = `${technology}-${difficulty}`;
  if (questionBanks[key]) return questionBanks[key];

  // Fallback: generate generic questions for the technology
  const questions: Question[] = [];
  for (let i = 1; i <= 20; i++) {
    const types: Question["type"][] = ["mcq", "scenario", "conceptual"];
    const type = types[i % 3];
    questions.push({
      id: i,
      question: `${difficulty} ${technology} Question ${i}: What is a key concept related to ${technology} at the ${difficulty.toLowerCase()} level?`,
      options: [
        `Correct answer for ${technology} Q${i}`,
        `Distractor option A for Q${i}`,
        `Distractor option B for Q${i}`,
        `Distractor option C for Q${i}`,
      ],
      correctAnswer: 0,
      explanation: `This tests your understanding of ${technology} at the ${difficulty.toLowerCase()} level. The correct answer demonstrates fundamental knowledge required for this topic.`,
      type,
    });
  }
  return questions;
}

export function getPerformanceLevel(score: number): { level: string; color: string } {
  if (score >= 80) return { level: "Excellent", color: "text-success" };
  if (score >= 60) return { level: "Good", color: "text-accent" };
  return { level: "Needs Improvement", color: "text-destructive" };
}

export function generateFeedback(result: TestResult): string {
  const { technology, scorePercentage, difficulty } = result;
  if (scorePercentage >= 90) {
    return `Outstanding performance! You demonstrate expert-level knowledge in ${technology} at the ${difficulty} level. You have a strong grasp of both theoretical concepts and practical applications.`;
  }
  if (scorePercentage >= 70) {
    return `Good job! You have a solid foundation in ${technology}. To reach the next level, focus on the questions you missed and review the explanations provided. Consider practicing more ${difficulty.toLowerCase()}-level scenarios.`;
  }
  if (scorePercentage >= 50) {
    return `You have a basic understanding of ${technology}, but there's room for improvement. Review the core concepts and practice with more examples. Consider starting with a lower difficulty level to build stronger foundations.`;
  }
  return `You need more practice with ${technology}. We recommend reviewing the fundamentals and studying the explanations for each question. Start with beginner-level resources and gradually work your way up.`;
}
